LVNOD-44_Create_Profile_model,_migration_and_seeders
Lv-237-NodeJS/api.da-mi pull request #17
Opened 2017-05-23 18:25 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-26)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-44)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @denisbodnar

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

- created profile model (without associations and validations)
- added migration file for profile model
- added seed file for profile model

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-05-23 18:35 UTC, denisbodnar submitted a review, later dismissed

2017-05-23 18:35 UTC, denisbodnar commented on server/seeders/20170523093919-unnamed-seeder.js
> +};
add a new line

2017-05-23 18:35 UTC, denisbodnar commented on server/migrations/20170522215056-create-profile.js
> +'use strict';
add an empty line

2017-05-23 19:27 UTC, denisbodnar submitted a review, later dismissed

2017-05-23 20:06 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-05-23 20:11 UTC, yarvanya submitted a review, later dismissed

2017-05-23 20:11 UTC, yarvanya commented on server/seeders/20170523093919-unnamed-seeder.js
> +};
Add new empty line

2017-05-23 20:11 UTC, yarvanya commented on server/models/index.js
> +module.exports = db;
This file has already created by Yuriy

2017-05-23 20:14 UTC, denisbodnar submitted a review, later dismissed

2017-05-25 00:39 UTC, 4asof4ik commented on server/seeders/profile.seed.js
> +        last_name: "Smith"
Add info for user country....

2017-05-25 00:39 UTC, 4asof4ik commented on server/routes/profile.router.js
> +  app.get('/api/profiles', profileController.list);
We have one profile for user

2017-05-25 00:49 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +  list(req, res) { // Display list of all profiles
Drop this method

2017-05-25 00:49 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +  destroy(req, res){  // DELETE single profile
Profile can be deleted only if user delet his account so this method can be dropped too

2017-05-25 00:49 UTC, 4asof4ik commented on server/models/profile.model.js
> +        Profiles.belongsTo(models.users, {
Profile and User

2017-05-25 00:52 UTC, 4asof4ik commented on server/models/profile.model.js
> +  const profile = sequelize.define('profile', {
First latter should be in uppercase

2017-05-25 00:52 UTC, 4asof4ik commented on server/models/profile.model.js
> +  return profile;
And here  uppercase

2017-05-25 08:42 UTC, 4asof4ik requested changes

2017-05-25 08:42 UTC, 4asof4ik commented on server/migrations/20170522215056-create-profile.js
> +    return queryInterface.dropTable('profiles');
Profiles

2017-05-25 08:42 UTC, 4asof4ik commented on server/migrations/20170522215056-create-profile.js
> +    return queryInterface.createTable('profiles', {
Profiles

2017-05-25 08:42 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +const profile = require('../models').profile;
Check if need use require('../models').Profile

2017-05-25 22:52 UTC, yurii-kokhalevych commented on server/controllers/profile.controller.js
> +// const Profile = require('../models/profile.model');
drop comment

2017-05-25 22:52 UTC, yurii-kokhalevych commented on server/migrations/20170525184235-create-profile.js
> +};
add line

2017-05-25 22:52 UTC, yurii-kokhalevych commented on server/models/profile.model.js
> +  var Profile = sequelize.define('Profile', {
why var?

2017-05-25 22:52 UTC, yurii-kokhalevych commented on server/models/profile.model.js
>      },
drop comments

2017-05-25 22:52 UTC, yurii-kokhalevych commented on server/routes/index.js
> +};
add line

2017-05-25 23:22 UTC, yuliannakorol commented on server/models/profile.model.js
> +  var Profile = sequelize.define('Profile', {
this was auto-generated by {{sequelize model:create}}

2017-05-26 09:15 UTC, denisbodnar submitted a review, later dismissed

2017-05-26 21:55 UTC, 4asof4ik requested changes

2017-05-26 21:55 UTC, 4asof4ik commented on server/seeders/profile.seed.js
> +
drop

2017-05-26 21:55 UTC, 4asof4ik commented on server/routes/index.js
> +  app.get('/api/profiles/:id', profileController.retrieve);
should be profile because a user has one profile

2017-05-26 21:55 UTC, 4asof4ik commented on server/app.js
> +require('./routes/profile.router')(app);
??

2017-05-26 21:55 UTC, 4asof4ik commented on server/models/profile.model.js
> +      },
align

2017-05-26 21:55 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +      return profile.update({
find the better way

2017-05-27 10:10 UTC, lhalam commented on server/controllers/profile.controller.js
> +// const Profile = require('../models/profile.model');
delete comment

2017-05-27 10:10 UTC, lhalam commented on server/controllers/profile.controller.js
> +        return res.status(404).send({ message: 'Profile Not Found'});
remove extra spaces

2017-05-27 10:10 UTC, lhalam commented on server/controllers/profile.controller.js
> +        return res.status(404).send({
comply with one style

2017-05-27 10:10 UTC, lhalam commented on server/models/profile.model.js
> +      associate: function(models) {
empty implementation? is it necessary?

2017-05-27 10:10 UTC, lhalam commented on server/routes/profile.router.js
> +// const profileController = require('../controllers/profile.controller');
delete comments

2017-05-27 10:10 UTC, lhalam commented on server/routes/index.js
> +  app.get('/api/profiles/:id', profileController.retrieve);
could be better use user_id?

2017-05-29 07:41 UTC, Vovk-Nazar requested changes

2017-05-29 07:41 UTC, Vovk-Nazar commented on server/controllers/profile.controller.js
> +        first_name: req.body.first_name || profile.first_name,
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

2017-05-29 15:08 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 08:48 UTC, closed without merging