Сreated model of the user
Lv-237-NodeJS/api.da-mi pull request #18
Opened 2017-05-25 20:12 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-27)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

First, I have created the model and migration.
Then I've created seed file for user model. After that all needed controllers with its routes.

## CHECK LIST

- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-05-25 20:17 UTC, omaik commented on server/controllers/users.js
> +        email: req.body.email,
I think you can do this in better way

2017-05-25 20:19 UTC, shyyka submitted a review, later dismissed

2017-05-25 20:32 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-05-25 20:37 UTC, omaik commented on server/migrations/20170524175710-create-user.js
> +      created_at: {
do you have something like `timestamps` ? it creates both `created_at` and `updated_at` fields

2017-05-26 22:07 UTC, 4asof4ik requested changes

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +          .update({
and here

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +          return res.status(400).send({
status should be 404 if not  found

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +'use strict';
rename file

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +      .findById(req.params.id, {})
empty object???

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +      .then((user) => {
if one argument drop () around a user

2017-05-26 22:07 UTC, 4asof4ik commented on server/routes/index.js
> +    message: 'Welcome to the Da - Mi project !!!',
drop comma in the end of line

2017-05-26 22:07 UTC, 4asof4ik commented on server/routes/index.js
> +module.exports = (app) => {
()

2017-05-26 22:07 UTC, 4asof4ik commented on server/models/user.js
> +        len: [6,20]
add validation for a-zA-Z 0-9 and !@#

2017-05-26 22:07 UTC, 4asof4ik commented on server/controllers/users.js
> +      .catch((error) => res.status(400).send(error));
() check all code

2017-05-31 19:47 UTC, closed without merging