Set jscs lint rules
Lv-237-NodeJS/api.da-mi pull request #20
Opened 2017-05-26 06:45 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-28)

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

I've installed jscs lint for our project and added some rules.

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-05-26 07:12 UTC, denisbodnar submitted a review, later dismissed

2017-05-26 07:54 UTC, shyyka submitted a review, later dismissed

2017-05-26 08:45 UTC, AlbaMontis submitted a review, later dismissed

2017-05-26 22:08 UTC, 4asof4ik requested changes

2017-05-26 22:08 UTC, 4asof4ik commented on .travis.yml
> +  - "6"
should be only 7

2017-05-27 09:48 UTC, 4asof4ik approved these changes

2017-05-27 11:59 UTC, denisbodnar approved these changes

2017-05-27 13:49 UTC, shyyka approved these changes

2017-05-27 14:35 UTC, merged