LVNOD-26-Create Profile model
Lv-237-NodeJS/api.da-mi pull request #22
Opened 2017-05-31 08:07 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-26)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-44, https://ssu-jira.softserveinc.com/browse/LVNOD-45)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @denisbodnar

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue
- Created profile model
- generated migration
- created controller for retrieving and updating profile
- created routes for profile controller 
- created profile seed file

2017-05-31 08:54 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-05-31 09:00 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 09:06 UTC, yarvanya submitted a review, later dismissed

2017-05-31 14:20 UTC, denisbodnar submitted a review, later dismissed

2017-05-31 18:34 UTC, yarvanya submitted a review, later dismissed

2017-05-31 21:08 UTC, 4asof4ik requested changes

2017-05-31 21:08 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +const Profile = require('../../config/db').Profile;
maybe it should be model but not config/db

2017-05-31 21:08 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +      let updateProfile = Object.assign({}, req.body);
should be not empty object but  profile
and in 26 line you can drop  || profile

2017-05-31 21:08 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +        return res.status(555).send(error);
555? where you find  this status??

2017-05-31 22:08 UTC, denisbodnar approved these changes

2017-05-31 22:11 UTC, yurii-kokhalevych approved these changes

2017-06-01 08:29 UTC, 4asof4ik approved these changes

2017-06-01 08:32 UTC, merged