Lvnod 60 create mailer
Lv-237-NodeJS/api.da-mi pull request #25
Opened 2017-06-01 23:00 UTC by shyyka

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-02 06:48 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-02 07:00 UTC, denisbodnar submitted a review, later dismissed

2017-06-02 07:00 UTC, denisbodnar commented on server/templates/mailer/activation.html
> +	<title>Da-Mi</title>
Use spaces, not tabs

2017-06-02 07:41 UTC, 4asof4ik requested changes

2017-06-02 07:41 UTC, 4asof4ik commented on server/helper/mailer.js
> +const nodemailer = require('nodemailer');
add nodemailer into package.json

2017-06-02 07:41 UTC, 4asof4ik commented on server/helper/mailer.js
> +          function(err, html) {
use ES6 => func

2017-06-02 07:41 UTC, 4asof4ik commented on server/helper/mailer.js
> +    fs.readFile(path.join('./server/templates/mailer/' + _name + '.html'), {
should be views but not templates

2017-06-02 07:41 UTC, 4asof4ik commented on server/helper/mailer.js
> +            transport.sendMail(mailOptions, function(error, response) {
ES6

2017-06-02 07:41 UTC, 4asof4ik commented on server/helper/mailer.js
> +      readHTMLTemplate(_template, function(err, html) {
ES6

2017-06-03 08:08 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-03 11:00 UTC, shyyka commented on server/helper/mailer.js
> +const nodemailer = require('nodemailer');
done.

2017-06-03 11:03 UTC, denisbodnar submitted a review, later dismissed

2017-06-03 11:23 UTC, yuliannakorol submitted a review, later dismissed

2017-06-03 11:39 UTC, denisbodnar submitted a review, later dismissed

2017-06-03 16:59 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-05 06:43 UTC, omaik commented on server/helper/mailer.js
> +        from: '"Da-Mi" <no-reply@da-mi.com>',
How do you plan to make it work on production?
Have you bought SES?

2017-06-05 12:05 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-05 12:34 UTC, yuliannakorol submitted a review, later dismissed

2017-06-05 13:32 UTC, lhalam reviewed
todo

2017-06-05 13:32 UTC, lhalam commented on server/helper/mailer.js
> +    port: 587,
host and port move to config

2017-06-05 13:32 UTC, lhalam commented on server/helper/mailer.js
> +        return console.error(err);
use logger

2017-06-05 13:32 UTC, lhalam commented on server/helper/mailer.js
> +        from: '"Da-Mi" <dami.serv@gmail.com>',
move to config

2017-06-05 13:32 UTC, lhalam commented on server/helper/mailer.js
> +          cid: 'bonsai@kreata.ee'
move to config or constant

2017-06-05 17:32 UTC, denisbodnar submitted a review, later dismissed

2017-06-05 18:39 UTC, 4asof4ik approved these changes

2017-06-05 18:42 UTC, 4asof4ik approved these changes

2017-06-05 20:20 UTC, denisbodnar approved these changes

2017-06-05 20:24 UTC, merged