Lvnod 63 create activation for user via email
Lv-237-NodeJS/api.da-mi pull request #26
Opened 2017-06-03 19:07 UTC by avoytovich

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-03 20:55 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-03 22:07 UTC, yuliannakorol submitted a review, later dismissed

2017-06-04 07:43 UTC, yarvanya submitted a review, later dismissed

2017-06-04 11:41 UTC, 4asof4ik requested changes

2017-06-04 11:41 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        return res.status(404).send({message: 'User Not Found'});
Create file with messages and use them.

2017-06-07 15:03 UTC, lhalam commented on server/controllers/activation.controller.js
> +    let token = req.headers['x-access-token'];
marker must be Url

2017-06-07 15:03 UTC, lhalam commented on server/routes/index.js
> +  app.get('/api/user/token', activationController.activation);
/api/user/token => /api/user/**:token**

2017-06-07 15:03 UTC, lhalam commented on server/controllers/activation.controller.js
> +    let activUser = {
move to the config

2017-06-07 15:08 UTC, yarvanya submitted a review, later dismissed

2017-06-07 15:11 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-07 16:11 UTC, avoytovich commented on server/controllers/activation.controller.js
> +    let token = req.headers['x-access-token'];
let token = '/api/user/token'; Любомир, ти так маєш на увазі?

2017-06-07 23:03 UTC, yuliannakorol submitted a review, later dismissed

2017-06-08 03:46 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-08 08:03 UTC, yarvanya submitted a review, later dismissed

2017-06-08 11:15 UTC, 4asof4ik requested changes

2017-06-08 11:15 UTC, 4asof4ik commented on server/views/emails/activated/style.scss
> +@import "../common.scss";
Why you create this and other files

2017-06-08 13:30 UTC, lhalam commented on server/controllers/activation.controller.js
> +const activUser = require(`${__dirname}/../../config/config.json`).activUser;
use `.`  not ${__dirname}

2017-06-08 13:30 UTC, lhalam commented on server/controllers/activation.controller.js
> +      mailerHelper(activUser, 'notvalid');
return res.status not send mail

2017-06-08 13:30 UTC, lhalam commented on server/controllers/activation.controller.js
> +        mailerHelper(activUser, 'notcreate');
send res

2017-06-08 13:30 UTC, lhalam commented on server/controllers/activation.controller.js
> +          mailerHelper(activUser, 'repeatactiv');
return res.status(400)

2017-06-09 06:37 UTC, avoytovich commented on server/views/emails/activated/style.scss
> +@import "../common.scss";
for import style in .hbs

2017-06-09 06:53 UTC, yarvanya submitted a review, later dismissed

2017-06-09 16:24 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-09 18:23 UTC, yuliannakorol submitted a review, later dismissed

2017-06-09 20:30 UTC, yarvanya submitted a review, later dismissed

2017-06-10 05:58 UTC, 4asof4ik requested changes

2017-06-10 05:58 UTC, 4asof4ik commented on server/controllers/activation.controller.js
> +      res.status(401).send(message.linkNotValid);
Incorrect status

2017-06-10 05:58 UTC, 4asof4ik commented on server/controllers/index.js
You don't need thIs controller

2017-06-10 07:15 UTC, avoytovich commented on server/controllers/activation.controller.js
> +      res.status(401).send(message.linkNotValid);
498 Invalid Token??
it will be done...

2017-06-10 07:27 UTC, avoytovich commented on server/controllers/index.js
ok, i will remove its from index...thank)) I mounted it as usual)), and didn't consider its need...

2017-06-10 10:29 UTC, yarvanya submitted a review, later dismissed

2017-06-10 14:14 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-10 15:28 UTC, yuliannakorol submitted a review, later dismissed

2017-06-12 10:49 UTC, lhalam commented on server/controllers/activation.controller.js
> +const {mailer} = require('./../helper');
merge 5 and 8 line

2017-06-12 10:49 UTC, lhalam commented on server/controllers/activation.controller.js
> +          user.update({
merge user update logic

2017-06-12 11:36 UTC, yarvanya submitted a review, later dismissed

2017-06-12 11:49 UTC, yuliannakorol submitted a review, later dismissed

2017-06-12 13:48 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-12 20:54 UTC, yarvanya submitted a review, later dismissed

2017-06-12 20:57 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-12 21:20 UTC, yuliannakorol submitted a review, later dismissed

2017-06-12 22:05 UTC, 4asof4ik requested changes

2017-06-12 22:05 UTC, 4asof4ik commented on server/controllers/activation.controller.js
> +  activation(req, res) {
controller for one action?

2017-06-12 22:05 UTC, 4asof4ik commented on server/views/emails/activated/style.scss
> +@import "../common.scss";
where your styles?

2017-06-12 22:05 UTC, 4asof4ik commented on server/helper/mailer.js
> +const secret = require('./../../config/mailerConfig.json');
string is bad idea

2017-06-12 22:05 UTC, 4asof4ik commented on server/controllers/activation.controller.js
> +const {mailer, message} = require('./../helper');
space after { and before }

2017-06-12 22:05 UTC, 4asof4ik commented on server/controllers/activation.controller.js
> +const activUser = require(`./../../config/config.json`).activUser;
what is that?

2017-06-12 22:30 UTC, avoytovich commented on server/helper/mailer.js
> +const secret = require('./../../config/mailerConfig.json');
if i stay this in previously stated it will generate a warn when our application will be boot..i can change this if it is not so big deal, does it?

2017-06-12 22:38 UTC, avoytovich commented on server/controllers/activation.controller.js
> +const {mailer, message} = require('./../helper');
doesn't work with linter and i think with travis also, does it?

2017-06-12 22:39 UTC, avoytovich commented on server/controllers/activation.controller.js
> +const activUser = require(`./../../config/config.json`).activUser;
will be remove

2017-06-12 23:03 UTC, avoytovich commented on server/controllers/activation.controller.js
> +  activation(req, res) {
which controller will be better for use?...or maybe it doesn't matter...because route still stay same as is exists?

2017-06-13 12:14 UTC, avoytovich commented on server/controllers/activation.controller.js
> +const {mailer, message} = require('./../helper');
Done

2017-06-13 12:28 UTC, avoytovich commented on server/helper/mailer.js
> +const secret = require('./../../config/mailerConfig.json');
ok i will change it in previously state. Done

2017-06-13 23:32 UTC, avoytovich commented on server/views/emails/activated/style.scss
> +@import "../common.scss";
in common.scss

2017-06-14 03:44 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-14 07:19 UTC, yarvanya submitted a review, later dismissed

2017-06-14 08:12 UTC, yuliannakorol submitted a review, later dismissed

2017-06-14 10:59 UTC, Vovk-Nazar requested changes

2017-06-14 10:59 UTC, Vovk-Nazar commented on server/controllers/auth.controller.js
> +        res.status(404).send(message.userNotValid);
userNotFound

2017-06-14 10:59 UTC, Vovk-Nazar commented on server/controllers/auth.controller.js
> +          res.status(200).send(message.linkAlreadyActivated);
succesActivation

2017-06-14 11:10 UTC, avoytovich commented on server/controllers/auth.controller.js
> +        res.status(404).send(message.userNotValid);
Done

2017-06-14 11:23 UTC, avoytovich commented on server/controllers/auth.controller.js
> +          res.status(200).send(message.linkAlreadyActivated);
this message don't use to success activation, it used to link which was double clicked by user in email, should i still change it?

2017-06-14 11:44 UTC, avoytovich commented on server/controllers/auth.controller.js
> +          res.status(200).send(message.linkAlreadyActivated);
i can change status at 418...???

2017-06-14 17:36 UTC, yarvanya submitted a review, later dismissed

2017-06-14 17:38 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-14 18:16 UTC, yuliannakorol submitted a review, later dismissed

2017-06-14 20:26 UTC, 4asof4ik approved these changes

2017-06-14 20:26 UTC, 4asof4ik commented on server/app.js
> +app.use('/api/+(?!auth),/api/+(?!/user/activation)/?*', function(req, res, next) {
add space after comma

2017-06-14 20:32 UTC, avoytovich commented on server/app.js
> +app.use('/api/+(?!auth),/api/+(?!/user/activation)/?*', function(req, res, next) {
Done

2017-06-14 20:45 UTC, yarvanya approved these changes

2017-06-14 20:48 UTC, merged