LVNOD-73 - BE - Create user controller for retrieving profile data
Lv-237-NodeJS/api.da-mi pull request #29
Opened 2017-06-07 13:43 UTC by yuliannakorol

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-71)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-73)

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue
Add new controller in user.controller file to return data from user and profile tables

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-07 13:51 UTC, denisbodnar submitted a review, later dismissed

2017-06-07 13:54 UTC, AlbaMontis submitted a review, later dismissed

2017-06-07 15:58 UTC, avoytovich submitted a review, later dismissed

2017-06-07 16:39 UTC, 4asof4ik requested changes

2017-06-07 16:39 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        data.email = user.email;
Object.assign

2017-06-07 22:51 UTC, avoytovich submitted a review, later dismissed

2017-06-08 12:09 UTC, avoytovich approved these changes

2017-06-08 12:21 UTC, denisbodnar approved these changes

2017-06-08 13:11 UTC, lhalam approved these changes

2017-06-08 13:16 UTC, merged