Lvnod 65 create model event
Lv-237-NodeJS/api.da-mi pull request #31
Opened 2017-06-07 23:40 UTC by yarvanya

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-65)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-66)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-67)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

First, I've created model for the Event model, then its seed and sequelize automatially generated migration for the model.
Second, I've created controller to this model with all needed methods: create,update,destroy,list and retrieve(list by id), and added routes for it.
Then I've added some change for user model and corrected some small mistakes.

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-08 07:43 UTC, denisbodnar submitted a review, later dismissed

2017-06-08 07:43 UTC, denisbodnar commented on server/controllers/index.js
> +const eventes = require('./event.controller');
events

2017-06-08 07:43 UTC, denisbodnar commented on server/controllers/index.js
> +  eventes
events

2017-06-08 12:22 UTC, denisbodnar submitted a review, later dismissed

2017-06-10 06:02 UTC, 4asof4ik requested changes

2017-06-10 06:02 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +    let decoder;
Why  you check token agen

2017-06-10 06:02 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +    let decoder;
Check token in one place

2017-06-10 11:47 UTC, yarvanya commented on server/controllers/event.controller.js
> +    let decoder;
I have understood, sorry, I'll correct it))

2017-06-10 14:15 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-10 14:34 UTC, denisbodnar submitted a review, later dismissed

2017-06-10 16:51 UTC, yuliannakorol submitted a review, later dismissed

2017-06-12 21:46 UTC, 4asof4ik requested changes

2017-06-12 21:46 UTC, 4asof4ik commented on server/models/event.model.js
> +    hooks: {
we will be using this hooks in each model, so we don't need this copy paste from model to model

2017-06-12 21:46 UTC, 4asof4ik commented on server/models/event.model.js
> +      type: DataTypes.DATE
required

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +            message: 'Event has not found! Please try again!',
all messages should be in messages file

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +          let needEventProperties = Object.assign({}, {
find a better way

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +    let assignEvent = Object.assign({}, req.body, {owner: decoded.id});
get owner id from request params

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +        if (event.owner !== decoded.id || !event)  {
req.params.id (owner id)
decoded.id (owner id) ??

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +const secret = require('./../../config/jwt.secretkey.json');
5-6 added but not used

2017-06-12 21:46 UTC, 4asof4ik commented on server/controllers/event.controller.js
> +      where: {owner: decoded.id}
check all decoded

2017-06-13 14:02 UTC, yarvanya commented on server/controllers/event.controller.js
> +    let assignEvent = Object.assign({}, req.body, {owner: decoded.id});
Here it is impossible to do it.

2017-06-13 14:02 UTC, yarvanya commented on server/models/event.model.js
> +    hooks: {
It will be another task for all back-end project, because, now, we have its hooks on dev branch.

2017-06-14 08:10 UTC, denisbodnar submitted a review, later dismissed

2017-06-14 08:37 UTC, yuliannakorol submitted a review, later dismissed

2017-06-14 14:37 UTC, denisbodnar approved these changes

2017-06-14 14:38 UTC, yurii-kokhalevych approved these changes

2017-06-14 14:41 UTC, yuliannakorol approved these changes

2017-06-14 14:42 UTC, merged