Lvnod 105 create controller for registration
Lv-237-NodeJS/api.da-mi pull request #32
Opened 2017-06-11 07:40 UTC by yurii-kokhalevych

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-105)

## Code reviewers

- [ ] @yarvanya
- [ ] @denisbodnar
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-06-11 10:06 UTC, denisbodnar submitted a review, later dismissed

2017-06-11 10:48 UTC, yuliannakorol submitted a review, later dismissed

2017-06-12 06:50 UTC, yarvanya submitted a review, later dismissed

2017-06-12 20:19 UTC, 4asof4ik requested changes

2017-06-12 20:19 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +  signup(req, res) {
this should be in user.controller as create action

2017-06-12 20:19 UTC, 4asof4ik commented on server/routes/index.js
> +  app.post('/api/auth/Signup', authController.signup);
create user action

2017-06-12 22:11 UTC, 4asof4ik requested changes

2017-06-12 22:11 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +  signup(req, res) {
should be create

2017-06-12 22:11 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        res.status(422).send('That email address is already in use.');
into messages

2017-06-12 22:11 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +    User.findOne({where: {email: req.body.email}}).then(user => {
User.findOne({
    where: {
        email: req.body.email
     }
}).then(user => {

2017-06-12 23:56 UTC, yuliannakorol submitted a review, later dismissed

2017-06-13 00:36 UTC, yuliannakorol submitted a review, later dismissed

2017-06-14 13:19 UTC, yarvanya submitted a review, later dismissed

2017-06-14 13:20 UTC, denisbodnar submitted a review, later dismissed

2017-06-14 16:49 UTC, denisbodnar submitted a review, later dismissed

2017-06-14 17:37 UTC, yarvanya submitted a review, later dismissed

2017-06-14 18:14 UTC, yuliannakorol submitted a review, later dismissed

2017-06-14 22:09 UTC, yarvanya submitted a review, later dismissed

2017-06-14 22:14 UTC, denisbodnar submitted a review, later dismissed

2017-06-15 12:11 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 15:19 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 15:20 UTC, denisbodnar submitted a review, later dismissed

2017-06-15 16:51 UTC, yarvanya submitted a review, later dismissed

2017-06-15 21:20 UTC, 4asof4ik requested changes

2017-06-15 21:20 UTC, 4asof4ik commented on server/routes/index.js
> +  app.post('/api/users/', userController.create);
drop last /

2017-06-15 21:20 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +          res.status(201).send(user);
why you send user?

2017-06-16 12:44 UTC, yarvanya submitted a review, later dismissed

2017-06-16 13:02 UTC, denisbodnar submitted a review, later dismissed

2017-06-16 13:13 UTC, yuliannakorol submitted a review, later dismissed

2017-06-16 13:28 UTC, lhalam reviewed
update logic of a relatively new field in the User model

2017-06-16 13:28 UTC, lhalam commented on server/controllers/user.controller.js
> +      if (user) {
update logic of a relatively new field in the User model

2017-06-16 20:59 UTC, yarvanya submitted a review, later dismissed

2017-06-16 20:59 UTC, denisbodnar submitted a review, later dismissed

2017-06-17 09:58 UTC, yuliannakorol submitted a review, later dismissed

2017-06-17 22:02 UTC, 4asof4ik requested changes

2017-06-17 22:02 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +    User.findOne({
the user is not created yet. what do you want to find?

2017-06-17 22:02 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +    .then(user => {
the user is undefined here

2017-06-17 22:02 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +          id: user.id,
here undefined.id will be error

2017-06-17 22:02 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        User.create(assignUser)
user creating here

2017-06-19 13:39 UTC, yarvanya submitted a review, later dismissed

2017-06-19 14:53 UTC, yuliannakorol submitted a review, later dismissed

2017-06-19 20:14 UTC, yarvanya submitted a review, later dismissed

2017-06-19 23:04 UTC, yarvanya submitted a review, later dismissed

2017-06-20 19:45 UTC, denisbodnar submitted a review, later dismissed

2017-06-20 19:45 UTC, denisbodnar commented on server/helper/messages.js
> +  linkAlreadyActivated: 'Link has already actived!',
activated

2017-06-20 19:49 UTC, yarvanya submitted a review, later dismissed

2017-06-20 19:56 UTC, yuliannakorol submitted a review, later dismissed

2017-06-20 22:33 UTC, denisbodnar submitted a review, later dismissed

2017-06-21 06:31 UTC, yarvanya submitted a review, later dismissed

2017-06-21 08:45 UTC, yuliannakorol submitted a review, later dismissed

2017-06-21 20:12 UTC, yarvanya submitted a review, later dismissed

2017-06-21 20:17 UTC, denisbodnar submitted a review, later dismissed

2017-06-21 20:39 UTC, 4asof4ik requested changes

2017-06-21 20:39 UTC, 4asof4ik commented on server/routes/index.js
> +  app.post('/api/auth/users', userController.create);
drop change

2017-06-21 20:39 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +const { mailer } = require('./../helper');
add messages and const... here

2017-06-22 18:48 UTC, yarvanya approved these changes

2017-06-22 18:50 UTC, denisbodnar approved these changes

2017-06-22 19:05 UTC, 4asof4ik approved these changes

2017-06-22 19:33 UTC, yuliannakorol approved these changes

2017-06-22 21:15 UTC, merged