Lvnod 89 gift model
Lv-237-NodeJS/api.da-mi pull request #33
Opened 2017-06-11 14:25 UTC by denisbodnar

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-83)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-89)

## Code reviewers

- [ ] @yarvanya
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-11 16:42 UTC, yuliannakorol submitted a review, later dismissed

2017-06-11 18:21 UTC, shyyka submitted a review, later dismissed

2017-06-12 06:41 UTC, yarvanya submitted a review, later dismissed

2017-06-12 10:26 UTC, lhalam reviewed
migration file?

2017-06-12 17:37 UTC, shyyka submitted a review, later dismissed

2017-06-12 20:22 UTC, yarvanya approved these changes

2017-06-12 20:25 UTC, yuliannakorol approved these changes

2017-06-12 20:53 UTC, shyyka approved these changes

2017-06-12 22:08 UTC, 4asof4ik requested changes

2017-06-12 22:08 UTC, 4asof4ik commented on server/models/gift.model.js
> +      beforeCreate: (gift, options) => {
this 2 hooks should be common for all models

2017-06-13 12:55 UTC, denisbodnar commented on server/models/gift.model.js
> +      beforeCreate: (gift, options) => {
It would be a separate task.

2017-06-14 15:02 UTC, closed without merging