Lvnod 89 gift model migration seeds
Lv-237-NodeJS/api.da-mi pull request #38
Opened 2017-06-14 15:01 UTC by denisbodnar

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-14 16:21 UTC, yarvanya submitted a review, later dismissed

2017-06-14 16:45 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-14 17:35 UTC, yarvanya submitted a review, later dismissed

2017-06-14 20:49 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 13:23 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-15 13:27 UTC, yarvanya submitted a review, later dismissed

2017-06-15 15:28 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 21:14 UTC, 4asof4ik requested changes

2017-06-15 21:14 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +    console.log(req.params);
?

2017-06-15 21:14 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +          return res.status(400).send(messages.giftNotFound);
404 but not 400

2017-06-15 21:14 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +      if (gift.dataValues.event_id !== Number(req.params.id) || !gift) {
create a common function for this validation ( we use here, destroy  and retrieve)

2017-06-15 21:14 UTC, 4asof4ik commented on server/routes/index.js
> +  app.get('/api/event/:id/gift/:giftid', giftController.retrieve);
gift_id

2017-06-19 22:42 UTC, yarvanya submitted a review, later dismissed

2017-06-20 22:42 UTC, yurii-kokhalevych commented on server/controllers/gift.controller.js
> +const eventIsDraft = (eventId) => {
write without ()  - eventId

2017-06-21 23:06 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-21 23:11 UTC, yuliannakorol submitted a review, later dismissed

2017-06-23 13:24 UTC, yarvanya submitted a review, later dismissed

2017-06-23 13:31 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-23 13:56 UTC, yuliannakorol submitted a review, later dismissed

2017-06-23 16:54 UTC, omaik commented on server/controllers/gift.controller.js
> +const Gift = require('../../config/db').Gift;
Could you do something like following instead?
```js
const DB = require('../../config/db')
const Gift = DB.Gift
....
```
Now you requiring the same file 3 times which looks redundant.

2017-06-23 16:56 UTC, omaik commented on server/controllers/gift.controller.js
> +    let assignGift = Object.assign({}, req.body, {event_id: req.params.id});
better name would be `giftParams`

2017-06-23 18:14 UTC, yarvanya submitted a review, later dismissed

2017-06-23 18:14 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-23 19:04 UTC, yuliannakorol submitted a review, later dismissed

2017-06-23 21:33 UTC, 4asof4ik requested changes

2017-06-23 21:33 UTC, 4asof4ik commented on server/routes/index.js
> +  app.get('/api/event/:id/gifts', giftController.list);
events 32 and 33

2017-06-23 21:33 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +    .then(gift => isEventOwner(req.params.id, req.decoded.id, gift)
the only owner can create a gift, so why check that?

2017-06-23 21:33 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +    .then(gift => isEventOwner(req.params.id, req.decoded.id, gift)
gifts

2017-06-23 22:04 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +    .then(gift => isEventOwner(req.params.id, req.decoded.id, gift)
without this check any logged in user can create any gift in any event behind the UI

2017-06-23 22:05 UTC, denisbodnar commented on server/routes/index.js
> +  app.get('/api/event/:id/gifts', giftController.list);
but there next we have an id of that event

2017-06-24 06:09 UTC, yarvanya submitted a review, later dismissed

2017-06-24 21:16 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-27 04:51 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-27 06:23 UTC, yarvanya submitted a review, later dismissed

2017-06-28 11:37 UTC, yurii-kokhalevych approved these changes

2017-06-28 16:51 UTC, yuliannakorol approved these changes

2017-06-28 17:44 UTC, yarvanya approved these changes

2017-06-28 19:38 UTC, 4asof4ik approved these changes

2017-06-28 19:44 UTC, merged