LVNOD-80 Guest model.
Lv-237-NodeJS/api.da-mi pull request #39
Opened 2017-06-15 13:45 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-80)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-81)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-15 17:34 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-15 18:01 UTC, yuliannakorol submitted a review, later dismissed

2017-06-15 18:39 UTC, shyyka submitted a review, later dismissed

2017-06-15 20:39 UTC, 4asof4ik requested changes

2017-06-15 20:39 UTC, 4asof4ik commented on server/migrations/20170609125500-create-guest.js
> +        values: ['going', 'notgoing', 'maybe'],
undecided but not maybe

2017-06-15 20:39 UTC, 4asof4ik commented on server/migrations/20170609125500-create-guest.js
> +        defaultValue: null,
undecided not null

2017-06-15 20:39 UTC, 4asof4ik commented on server/migrations/20170609125500-create-guest.js
> +        allowNull: true
false

2017-06-15 20:39 UTC, 4asof4ik commented on server/models/guest.model.js
> +      values: ['going', 'notgoing', 'maybe'],
check migration comment

2017-06-16 10:09 UTC, yuliannakorol approved these changes

2017-06-16 10:11 UTC, shyyka approved these changes

2017-06-16 12:06 UTC, yurii-kokhalevych approved these changes

2017-06-16 13:12 UTC, merged