LVNOD-80 Added guest controller, routes, modified user.create
Lv-237-NodeJS/api.da-mi pull request #45
Opened 2017-06-19 21:38 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-80)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-116)

## Code reviewers

- [ ] @yarvanya
- [ ] @denisbodnar
- [ ] @shyyka

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-19 21:44 UTC, yarvanya submitted a review, later dismissed

2017-06-19 21:50 UTC, denisbodnar submitted a review, later dismissed

2017-06-19 22:09 UTC, 4asof4ik requested changes

2017-06-19 22:09 UTC, 4asof4ik commented on server/helper/passwordGenerator.js
> +    for (i = 0; i < 3; i++) {
let i = 0 maybe?

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +      res.send({guest: guests});
guests: guests

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +  retrieve(req, res) {
list

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +        const firstname = guest.User.Profile ? guest.User.Profile.first_name : '';
guest.User.Profile.first_name || ''

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +    .then((guests) => res.send({guests: guests}))
if one arg  we dont need ()

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +    const id = req.body.eventId;
eventID or somethink like that

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        .then(user => user ?
use && and ||

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +            Guest.create({
you have 20-23

2017-06-19 22:09 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +    .catch(err => res.status(404).send(error));
400

2017-06-19 22:21 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +  retrieve(req, res) {
Done.

2017-06-19 22:21 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +      res.send({guest: guests});
Done.

2017-06-19 22:23 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +        const firstname = guest.User.Profile ? guest.User.Profile.first_name : '';
Done.

2017-06-19 22:24 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +    .then((guests) => res.send({guests: guests}))
Done.

2017-06-19 22:24 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +    .catch(err => res.status(404).send(error));
Done.

2017-06-19 22:25 UTC, AlbaMontis commented on server/controllers/user.controller.js
> +    const id = req.body.eventId;
Done.

2017-06-19 22:32 UTC, AlbaMontis commented on server/helper/passwordGenerator.js
> +    for (i = 0; i < 3; i++) {
Done.

2017-06-20 06:00 UTC, denisbodnar approved these changes

2017-06-20 06:15 UTC, yarvanya approved these changes

2017-06-20 06:17 UTC, 4asof4ik approved these changes

2017-06-20 06:20 UTC, merged