BugFix - User retrieve method
Lv-237-NodeJS/api.da-mi pull request #49
Opened 2017-06-27 14:30 UTC by yuliannakorol

Bug Fix

## Code reviewers

- [ ] @denisbodnar
- [ ] @AlbaMontis
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change
fixed user-profile retrieve method

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR

2017-06-27 15:25 UTC, avoytovich submitted a review, later dismissed

2017-06-27 16:32 UTC, AlbaMontis submitted a review, later dismissed

2017-06-27 18:12 UTC, denisbodnar submitted a review, later dismissed

2017-06-28 08:58 UTC, 4asof4ik requested changes

2017-06-28 08:58 UTC, 4asof4ik commented on server/controllers/user.controller.js
>        if (!user) {
use && here

2017-06-28 08:58 UTC, 4asof4ik commented on server/controllers/user.controller.js
>          if (!profile) {
and here

2017-06-29 04:24 UTC, avoytovich submitted a review, later dismissed

2017-06-29 07:57 UTC, AlbaMontis submitted a review, later dismissed

2017-06-29 16:27 UTC, denisbodnar submitted a review, later dismissed

2017-06-30 06:50 UTC, 4asof4ik approved these changes

2017-06-30 06:50 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +          return (res.status(200).send(Object.assign({}, user.dataValues, profile.dataValues)));
arrow function by default has "return" you can check this

2017-06-30 07:22 UTC, yarvanya approved these changes

2017-06-30 07:23 UTC, denisbodnar approved these changes

2017-06-30 07:23 UTC, merged