Lvnod 118 create comment model controller migration
Lv-237-NodeJS/api.da-mi pull request #50
Opened 2017-06-29 02:37 UTC by shyyka

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @AlbaMontis
- [ ] @avoytovich

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)

2017-06-29 06:22 UTC, avoytovich submitted a review, later dismissed

2017-06-29 07:18 UTC, yarvanya submitted a review, later dismissed

2017-06-29 08:20 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +const mailer = require('./../helper/mailer');
You can grab all helpers from ('../helper') in one row.

2017-06-29 08:20 UTC, AlbaMontis commented on server/views/emails/commentReply/text.hbs
> +  Hello {{firstname}} {{lasttname}}!
"lastname".

2017-06-29 08:20 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +    if (!!req.body.parent_id) {
You can use && here.

2017-06-29 08:20 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +          id: req.body.parent_id
Isn't an id a unique field?

2017-06-29 08:20 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +          const firstname = item.User.Profile ? item.User.Profile.first_name : '';
const {first_name, last_name} = item.User.Profile || '';

2017-06-29 08:20 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +      return res.status(201).send(comment);
`comment => res.status(201).send(comment);`

2017-06-29 12:17 UTC, shyyka commented on server/controllers/comment.controller.js
> +const mailer = require('./../helper/mailer');
Ok

2017-06-29 12:34 UTC, shyyka commented on server/controllers/comment.controller.js
> +          const firstname = item.User.Profile ? item.User.Profile.first_name : '';
Done.

2017-06-29 12:39 UTC, shyyka commented on server/controllers/comment.controller.js
> +          id: req.body.parent_id
Refactored

2017-06-29 13:01 UTC, shyyka commented on server/controllers/comment.controller.js
> +      return res.status(201).send(comment);
Ok

2017-06-29 13:01 UTC, shyyka commented on server/controllers/comment.controller.js
> +    if (!!req.body.parent_id) {
Ok

2017-06-29 14:48 UTC, yarvanya submitted a review, later dismissed

2017-06-29 14:57 UTC, AlbaMontis submitted a review, later dismissed

2017-06-29 20:00 UTC, avoytovich submitted a review, later dismissed

2017-06-30 06:30 UTC, omaik commented on server/controllers/comment.controller.js
> +const URL = HOST + PORT;
I think better hold it in `constants` file as well

2017-06-30 06:31 UTC, omaik commented on server/controllers/comment.controller.js
> +const User = require('../../config/db').User;
You requiring the same file 5 times. Change to 1.

2017-06-30 06:32 UTC, omaik commented on server/controllers/comment.controller.js
> +    let assignComment = Object.assign({}, req.body, {gift_id: req.params.gift_id},
a better name would be `commentParams`

2017-06-30 07:34 UTC, 4asof4ik requested changes

2017-06-30 07:34 UTC, 4asof4ik commented on server/helper/mailer.js
> +    let url = 'http://' + _data.host + _data.route + (_data.token || '');
https://github.com/Lv-237-NodeJS/api.da-mi/pull/51 look here

2017-06-30 07:34 UTC, 4asof4ik commented on server/helper/mailer.js
> +        from: '"Da-Mi"' + '<' + secret.email + '>',
https://github.com/Lv-237-NodeJS/api.da-mi/pull/51

2017-06-30 07:34 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +        return res.status(404).send(messages.commentNotFound);
in arrow function return is by default

2017-06-30 18:35 UTC, avoytovich submitted a review, later dismissed

2017-06-30 19:32 UTC, yarvanya submitted a review, later dismissed

2017-07-01 11:59 UTC, AlbaMontis submitted a review, later dismissed

2017-07-01 18:55 UTC, 4asof4ik commented on server/migrations/20170623075621-create-comment.js
> +      user_id: {
Maybe guest ?

2017-07-01 18:57 UTC, 4asof4ik commented on server/migrations/20170623075621-create-comment.js
> +      user_id: {
Check this

2017-07-02 01:45 UTC, shyyka commented on server/migrations/20170623075621-create-comment.js
> +      user_id: {
As I understand, the guest is a user (Guest.id = User.id) and I'll get his values (email, first_name, last_name) from the table User and Profile, and with donor will be as well, they both have an opportunity to comment... I should think about this

2017-07-03 19:30 UTC, shyyka commented on server/controllers/comment.controller.js
> +const User = require('../../config/db').User;
Done.

2017-07-03 19:30 UTC, shyyka commented on server/controllers/comment.controller.js
> +const URL = HOST + PORT;
Done.

2017-07-03 19:30 UTC, shyyka commented on server/controllers/comment.controller.js
> +    let assignComment = Object.assign({}, req.body, {gift_id: req.params.gift_id},
Done.

2017-07-03 19:30 UTC, shyyka commented on server/controllers/comment.controller.js
> +        return res.status(404).send(messages.commentNotFound);
Done.

2017-07-05 07:56 UTC, 4asof4ik approved these changes

2017-07-06 05:57 UTC, 4asof4ik requested changes

2017-07-06 05:57 UTC, 4asof4ik commented on server/views/emails/commentReply/html.hbs
> +  <p class="center">Hello {{firstname}} {{lastname}}!</p>
camellCase check other file

2017-07-06 05:57 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +          const template = 'commentReply';
create constant for template name and subject check all controllers please

2017-07-06 21:07 UTC, shyyka commented on server/controllers/comment.controller.js
> +          const template = 'commentReply';
Done.

2017-07-07 16:08 UTC, shyyka commented on server/views/emails/commentReply/html.hbs
> +  <p class="center">Hello {{firstname}} {{lastname}}!</p>
Done

2017-07-08 22:57 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +      Comment.findById(req.body.parent_id, {
Create a const for req.body.parent_id.

2017-07-08 23:01 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +        if (comment.parent_id) {
Use && and ||.

2017-07-08 23:03 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +  .catch(error => res.status(400).send({message: error}));
We decided yesterday to use .json() for sending messages.

2017-07-08 23:04 UTC, shyyka commented on server/controllers/comment.controller.js
> +      Comment.findById(req.body.parent_id, {
Ok

2017-07-08 23:04 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +        comment.destroy();}
Put } into 102.

2017-07-09 07:11 UTC, yarvanya commented on server/controllers/comment.controller.js
> +      .then(comment => res.status(200).send({message: comment}))
Use json().

2017-07-09 07:11 UTC, yarvanya commented on server/models/comment.model.js
> +    paranoid: false,
Delete paranoid property, because it unneeded.
I'll correct it in another models.

2017-07-10 01:16 UTC, shyyka commented on server/models/comment.model.js
> +    paranoid: false,
Ok

2017-07-10 08:18 UTC, AlbaMontis submitted a review, later dismissed

2017-07-10 08:20 UTC, avoytovich submitted a review, later dismissed

2017-07-10 09:04 UTC, yarvanya submitted a review, later dismissed

2017-07-10 12:24 UTC, AlbaMontis submitted a review, later dismissed

2017-07-10 18:45 UTC, AlbaMontis submitted a review, later dismissed

2017-07-10 19:10 UTC, yarvanya submitted a review, later dismissed

2017-07-10 19:39 UTC, 4asof4ik requested changes

2017-07-10 19:39 UTC, 4asof4ik commented on server/helper/mailer.js
> +        from: `"Da-Mi"<${secret.email}>`,
" " ?

2017-07-10 19:39 UTC, 4asof4ik commented on server/models/comment.model.js
> +      allowNull: true
On front end you have validation add validation here too

2017-07-10 19:39 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +    comment.User.Profile.dataValues.avatar = (avatar !== null ?
&& and ||

2017-07-10 19:39 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +      .then(comments => {comments.forEach(comment => comment && comment.destroy());
use map
you don't need comment &&

2017-07-10 23:03 UTC, shyyka commented on server/helper/mailer.js
> +        from: `"Da-Mi"<${secret.email}>`,
Done

2017-07-10 23:03 UTC, shyyka commented on server/models/comment.model.js
> +      allowNull: true
Done

2017-07-10 23:03 UTC, shyyka commented on server/controllers/comment.controller.js
> +    comment.User.Profile.dataValues.avatar = (avatar !== null ?
Done

2017-07-10 23:04 UTC, shyyka commented on server/controllers/comment.controller.js
> +      .then(comments => {comments.forEach(comment => comment && comment.destroy());
Done

2017-07-10 23:25 UTC, AlbaMontis commented on server/helper/messages.js
> +  invitationsSended: 'Invitations were sended.',
It was 'invitations were sent.'

2017-07-10 23:25 UTC, AlbaMontis commented on server/helper/messages.js
> +  invitationsSended: 'Invitations were sended.',
Look at 18

2017-07-10 23:39 UTC, shyyka commented on server/helper/messages.js
> +  invitationsSended: 'Invitations were sended.',
i just go to drop

2017-07-11 04:45 UTC, yarvanya submitted a review, later dismissed

2017-07-11 08:15 UTC, AlbaMontis submitted a review, later dismissed

2017-07-11 10:27 UTC, avoytovich submitted a review, later dismissed

2017-07-12 13:31 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +    const {avatar} = comment.User.Profile.dataValues;
Fix indentation.

2017-07-12 13:38 UTC, yarvanya submitted a review, later dismissed

2017-07-12 13:47 UTC, AlbaMontis commented on server/controllers/comment.controller.js
> +      .then(() => res.status(204).json({'message': messages.commentDeleted}))
With status code 204 message will be not visible in response.

2017-07-12 13:49 UTC, AlbaMontis commented on server/migrations/20170623075621-create-comment.js
> +        references: {
Add `onDelete: 'CASCADE'`

2017-07-12 13:51 UTC, AlbaMontis commented on server/migrations/20170623075621-create-comment.js
> +        references: {
Add `onDelete: 'CASCADE'`

2017-07-13 22:17 UTC, avoytovich submitted a review, later dismissed

2017-07-14 09:43 UTC, yarvanya submitted a review, later dismissed

2017-07-15 08:42 UTC, AlbaMontis submitted a review, later dismissed

2017-07-15 15:05 UTC, yarvanya submitted a review, later dismissed

2017-07-15 15:20 UTC, AlbaMontis submitted a review, later dismissed

2017-07-15 20:41 UTC, AlbaMontis submitted a review, later dismissed

2017-07-15 20:42 UTC, yarvanya submitted a review, later dismissed

2017-07-16 08:01 UTC, yarvanya submitted a review, later dismissed

2017-07-16 09:41 UTC, AlbaMontis submitted a review, later dismissed

2017-07-16 14:56 UTC, avoytovich submitted a review, later dismissed

2017-07-17 08:19 UTC, 4asof4ik requested changes

2017-07-17 08:19 UTC, 4asof4ik commented on server/models/comment.model.js
> +      beforeCreate: (comment, options) => {
you have this hooks in helpers

2017-07-17 08:19 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +      comments.forEach(comment => {
map

2017-07-17 08:19 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +          parentComment.children ? parentComment.children.push(comment)
separate
......
? ...........
: ...........

2017-07-17 08:19 UTC, 4asof4ik commented on server/controllers/comment.controller.js
> +      .then(comment => res.status(200).send({comment}))
drop {}

2017-07-17 09:15 UTC, shyyka commented on server/models/comment.model.js
> +      beforeCreate: (comment, options) => {
Done.

2017-07-17 09:16 UTC, shyyka commented on server/controllers/comment.controller.js
> +      comments.forEach(comment => {
Done

2017-07-17 09:16 UTC, shyyka commented on server/controllers/comment.controller.js
> +          parentComment.children ? parentComment.children.push(comment)
Done

2017-07-17 09:16 UTC, shyyka commented on server/controllers/comment.controller.js
> +      .then(comment => res.status(200).send({comment}))
Done

2017-07-17 09:25 UTC, AlbaMontis approved these changes

2017-07-17 09:27 UTC, avoytovich approved these changes

2017-07-17 09:27 UTC, yarvanya approved these changes

2017-07-17 10:45 UTC, shyyka commented on server/models/comment.model.js
> +      beforeCreate: (comment, options) => {
With hooks outside sequelize didn't work properly

2017-07-17 19:23 UTC, 4asof4ik approved these changes

2017-07-17 20:08 UTC, merged