Lvnod 80 guest controller
Lv-237-NodeJS/api.da-mi pull request #51
Opened 2017-06-29 14:47 UTC by AlbaMontis

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-80)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-86)

## Code reviewers

- [ ] @yurii-kokhalevych
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-06-29 14:57 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-29 15:02 UTC, shyyka submitted a review, later dismissed

2017-06-29 15:41 UTC, yuliannakorol submitted a review, later dismissed

2017-06-30 07:11 UTC, 4asof4ik requested changes

2017-06-30 07:11 UTC, 4asof4ik commented on server/controllers/auth.controller.js
>          res.status(401).send('Email or password is not valid');
why if !user.is_activate response Email or password is not valid?

2017-06-30 07:11 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +      res.send({guests});
add status 200

2017-06-30 07:11 UTC, 4asof4ik commented on server/helper/mailer.js
> +        from: '"Da-Mi"' + '<' + secret.gmail.user + '>',
look at the line 25  use `${}`

2017-06-30 07:11 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +    const eventId = req.headers.referer.split('/')[4];
find in params

2017-06-30 11:37 UTC, AlbaMontis commented on server/controllers/user.controller.js
> +    const eventId = req.headers.referer.split('/')[4];
ok.

2017-06-30 11:38 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +      res.send({guests});
ok.

2017-06-30 11:45 UTC, AlbaMontis commented on server/helper/mailer.js
> +        from: '"Da-Mi"' + '<' + secret.gmail.user + '>',
ok.

2017-06-30 12:20 UTC, AlbaMontis commented on server/controllers/auth.controller.js
>          res.status(401).send('Email or password is not valid');
I'll fix it.

2017-06-30 13:21 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-06-30 15:24 UTC, shyyka submitted a review, later dismissed

2017-06-30 16:25 UTC, yuliannakorol submitted a review, later dismissed

2017-07-03 10:05 UTC, yuliannakorol submitted a review, later dismissed

2017-07-03 10:50 UTC, 4asof4ik requested changes

2017-07-03 10:50 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +        res.status(401).send(messages.loginDataNotValid) ||  !user.is_activate &&
after || 2 spaces

2017-07-03 10:50 UTC, 4asof4ik commented on server/controllers/auth.controller.js
>      User.findOne({where: {email: req.body.email}}).then(user => {
separat

2017-07-03 10:50 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +              id: user.id
and 20 line

2017-07-03 10:50 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        res.status(404).send(messages.userNotFound);
in one line without {} check all

2017-07-03 12:54 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-03 13:23 UTC, yuliannakorol submitted a review, later dismissed

2017-07-03 13:24 UTC, shyyka submitted a review, later dismissed

2017-07-03 21:54 UTC, 4asof4ik requested changes

2017-07-03 21:54 UTC, 4asof4ik commented on server/routes/index.js
>    app.get('/api/event/:id/guest/get', guestController.list);
why not :id/guests

2017-07-03 21:54 UTC, 4asof4ik commented on server/helper/mailer.js
>          text: sendMail.text,
It should be html or text, Check what is sendMail.text, please

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +        res.status(401).send(messages.loginDataNotValid) || !user.is_activate &&
why you add spaces in each line

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +const URL = constants.HOST + constants.PORT;
create this in const file

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +      res.status(200).send({guests});
drop {} and into line 17

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +          guests.forEach(guest => guest && guest.destroy());
drop {}

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/user.controller.js
>              Guest.create({
find or create maybe without findGuest(user.id, eventId) ?

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +          return {id: user.id, email: user.email};
this is arrow function return is already included

2017-07-03 21:54 UTC, 4asof4ik commented on server/controllers/user.controller.js
> +        Guest.findAll({
use cascade in the relationship  when you destroy user all guests with userId will be destroyed also

2017-07-04 12:25 UTC, AlbaMontis commented on server/routes/index.js
>    app.get('/api/event/:id/guest/get', guestController.list);
ok.

2017-07-04 12:26 UTC, AlbaMontis commented on server/controllers/user.controller.js
> +        Guest.findAll({
ok

2017-07-04 12:33 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +      res.status(200).send({guests});
ok.

2017-07-04 12:41 UTC, AlbaMontis commented on server/controllers/user.controller.js
>              Guest.create({
ok

2017-07-04 13:28 UTC, AlbaMontis commented on server/controllers/user.controller.js
> +          guests.forEach(guest => guest && guest.destroy());
I'll delete this row due to previous comment.

2017-07-04 13:28 UTC, AlbaMontis commented on server/controllers/auth.controller.js
> +        res.status(401).send(messages.loginDataNotValid) || !user.is_activate &&
Fixed.

2017-07-04 13:40 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +const URL = constants.HOST + constants.PORT;
ok.

2017-07-04 14:00 UTC, shyyka submitted a review, later dismissed

2017-07-04 14:05 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 14:10 UTC, yuliannakorol submitted a review, later dismissed

2017-07-04 19:22 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 19:25 UTC, shyyka submitted a review, later dismissed

2017-07-04 21:30 UTC, yuliannakorol submitted a review, later dismissed

2017-07-05 07:36 UTC, 4asof4ik requested changes

2017-07-05 07:36 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +      (!user || !passwordHash.verify(req.body.password, user.password)) &&
can you create function  which will be check (!user || !passwordHash.verify(req.body.password, user.password))  and return true or false

2017-07-05 07:36 UTC, 4asof4ik commented on server/controllers/guest.controller.js
> +            host: constants.URL,
in production it will be localhost:8080 it's okey?

2017-07-05 09:16 UTC, AlbaMontis commented on server/controllers/guest.controller.js
> +            host: constants.URL,
It will not.

2017-07-05 09:41 UTC, AlbaMontis commented on server/controllers/auth.controller.js
> +      (!user || !passwordHash.verify(req.body.password, user.password)) &&
Done.

2017-07-05 11:02 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-05 11:14 UTC, yuliannakorol submitted a review, later dismissed

2017-07-05 12:20 UTC, shyyka submitted a review, later dismissed

2017-07-05 12:40 UTC, shyyka approved these changes

2017-07-05 12:43 UTC, yurii-kokhalevych approved these changes

2017-07-05 12:49 UTC, yuliannakorol approved these changes

2017-07-06 05:48 UTC, 4asof4ik approved these changes

2017-07-06 06:09 UTC, merged