Resolving some issues LVNOD-63
Lv-237-NodeJS/api.da-mi pull request #52
Opened 2017-07-04 12:45 UTC by avoytovich

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

Redirecting user after activation via email

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  All reviewers agreed to merge the PR

2017-07-04 12:58 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 13:12 UTC, yarvanya submitted a review, later dismissed

2017-07-04 14:14 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 16:04 UTC, yarvanya submitted a review, later dismissed

2017-07-04 19:06 UTC, yuliannakorol submitted a review, later dismissed

2017-07-05 07:28 UTC, 4asof4ik requested changes

2017-07-05 07:28 UTC, 4asof4ik commented on server/controllers/auth.controller.js
> +              res.redirect('http://' + URL);
in production you will be having http://localhost:8080 ?

2017-07-05 19:06 UTC, avoytovich commented on server/controllers/auth.controller.js
> +              res.redirect('http://' + URL);
at the end i suppose...no

2017-07-09 19:06 UTC, yarvanya submitted a review, later dismissed

2017-07-09 19:09 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-09 19:14 UTC, yuliannakorol submitted a review, later dismissed

2017-07-09 22:07 UTC, 4asof4ik approved these changes

2017-07-10 08:03 UTC, yarvanya approved these changes

2017-07-10 08:04 UTC, merged