Add image to gift model and improve controller
Lv-237-NodeJS/api.da-mi pull request #53
Opened 2017-07-04 21:11 UTC by denisbodnar

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @AlbaMontis

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

2017-07-04 21:41 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: eventId, $and: {owner: userId}}})
You can return without word "return"

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Guest.findOne({where: {event_id: eventId, $and: {user_id: userId}}})
The same as above.

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Guest.findOne({where: {event_id: eventId, $and: {user_id: userId}}})
Also it looks like "$and" is unnecessary.

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: +eventId, $and: {status_event_id: 1}}})
The same as above.

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: +eventId, $and: {status_event_id: 1}}})
`+` is not a good practice. Use parseInt().

2017-07-04 22:04 UTC, AlbaMontis commented on server/controllers/gift.controller.js
>      let giftParams = Object.assign({}, req.body, {event_id: req.params.id});
It could be const.

2017-07-04 22:26 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: eventId, $and: {owner: userId}}})
In a concise body, only an expression is needed, and an implicit return is attached. In a block body, you must use an explicit return statement.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2017-07-04 22:31 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Guest.findOne({where: {event_id: eventId, $and: {user_id: userId}}})
$and is a Sequelize query operator

http://docs.sequelizejs.com/manual/tutorial/querying.html

2017-07-04 22:32 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: +eventId, $and: {status_event_id: 1}}})
this shortcut works for me

2017-07-04 22:36 UTC, denisbodnar commented on server/controllers/gift.controller.js
>      let giftParams = Object.assign({}, req.body, {event_id: req.params.id});
it is just a temporary value, changing with every request, so there is no need for it to be declared with const

2017-07-05 05:30 UTC, yarvanya submitted a review, later dismissed

2017-07-05 08:09 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Guest.findOne({where: {event_id: eventId, $and: {user_id: userId}}})
I know. But can't you write just `{where: {event_id: eventId, user_id: userId}}` it is the same but without useless $and operator.

2017-07-05 08:13 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: eventId, $and: {owner: userId}}})
Why can't you use concise body here?

2017-07-05 08:17 UTC, AlbaMontis commented on server/controllers/gift.controller.js
>      let giftParams = Object.assign({}, req.body, {event_id: req.params.id});
But you don't reassign it.
https://google.github.io/styleguide/jsguide.html#features-local-variable-declarations

2017-07-05 08:23 UTC, AlbaMontis commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: +eventId, $and: {status_event_id: 1}}})
![screenshot from 2017-07-05 11-22-27](https://user-images.githubusercontent.com/13887090/27855753-4e6e4f76-6174-11e7-840f-55d174dd7ffb.png)

2017-07-05 08:25 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Guest.findOne({where: {event_id: eventId, $and: {user_id: userId}}})
Maybe

2017-07-05 08:25 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: eventId, $and: {owner: userId}}})
Yep, good point

2017-07-05 08:25 UTC, denisbodnar commented on server/controllers/gift.controller.js
> +  return Event.findOne({where: {id: +eventId, $and: {status_event_id: 1}}})
I know about speed)

2017-07-05 08:26 UTC, denisbodnar commented on server/controllers/gift.controller.js
>      let giftParams = Object.assign({}, req.body, {event_id: req.params.id});
Ok then

2017-07-05 09:14 UTC, AlbaMontis submitted a review, later dismissed

2017-07-05 09:32 UTC, yarvanya submitted a review, later dismissed

2017-07-05 12:13 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-06 05:53 UTC, 4asof4ik requested changes

2017-07-06 05:53 UTC, 4asof4ik commented on server/controllers/gift.controller.js
> +    Gift.findOne({where: {id: req.params.gift_id, event_id: req.params.id}})
you have this code in 57 73 create common function this

2017-07-09 07:14 UTC, yarvanya submitted a review, later dismissed

2017-07-09 07:45 UTC, 4asof4ik approved these changes
Fix content and merge

2017-07-09 08:22 UTC, yarvanya submitted a review, later dismissed

2017-07-09 09:04 UTC, yarvanya approved these changes

2017-07-09 09:04 UTC, merged