Refactoring and fixes - Profile Controller
Lv-237-NodeJS/api.da-mi pull request #57
Opened 2017-07-08 14:00 UTC by yuliannakorol

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @denisbodnar 

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of change
Profile Controller - Code cleanup and refactoring

2017-07-08 14:27 UTC, 4asof4ik approved these changes

2017-07-08 14:27 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +    // const updateProfile = Object.assign({}, req.body);
?

2017-07-08 14:41 UTC, denisbodnar submitted a review, later dismissed

2017-07-08 20:22 UTC, 4asof4ik requested changes

2017-07-08 20:22 UTC, 4asof4ik commented on server/controllers/profile.controller.js
> +      profile || res.status(404).json(messages.profileError);
You forgot !  And use && and ||

2017-07-09 06:55 UTC, yarvanya approved these changes

2017-07-09 09:14 UTC, 4asof4ik approved these changes

2017-07-09 09:23 UTC, merged