LVNOD-140 Create Donor model && controller and migration
Lv-237-NodeJS/api.da-mi pull request #66
Opened 2017-07-12 13:01 UTC by avoytovich

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @yurii-kokhalevych
- [ ] @denisbodnar

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

Create Donor model with controller

## CHECK LIST
- [ ]  СI passed
- [ ]  All reviewers agreed to merge the PR

2017-07-12 13:13 UTC, yarvanya commented on server/models/donor.js
> +      paranoid: false,
Delete paranoid property.

2017-07-12 14:02 UTC, yarvanya submitted a review, later dismissed

2017-07-12 14:08 UTC, denisbodnar submitted a review, later dismissed

2017-07-12 14:22 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-14 21:02 UTC, yarvanya commented on server/migrations/20170712071623-create-donor.js
> +  up: function(queryInterface, Sequelize) {
Use arrow function.

2017-07-14 21:02 UTC, yarvanya commented on server/migrations/20170712071623-create-donor.js
> +  down: function(queryInterface, Sequelize) {
Use arrow function.

2017-07-14 21:02 UTC, yarvanya commented on server/models/donor.js
> +module.exports = function(sequelize, DataTypes) {
Use arrow function.

2017-07-14 21:02 UTC, yarvanya commented on server/models/donor.js
> +  var Donor = sequelize.define('Donor', {
Use const.

2017-07-15 07:45 UTC, yarvanya submitted a review, later dismissed

2017-07-15 08:53 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-15 10:33 UTC, denisbodnar commented on server/controllers/donor.controller.js
> +          gift.dataValues.status == 'hasOneDonor' &&
Use === everywhere

2017-07-15 10:33 UTC, denisbodnar commented on server/controllers/donor.controller.js
> +        .catch(error => res.status(400).send(error)) ||
What's the point of this check? Just send error message

2017-07-15 10:33 UTC, denisbodnar commented on server/controllers/donor.controller.js
> +                                    (result.donor[i - 1] = `Donor_${i++}: ` +
This should be on frontend, not here.

2017-07-15 12:13 UTC, avoytovich commented on server/controllers/donor.controller.js
> +        .catch(error => res.status(400).send(error)) ||
i rather would leave send error...because catch use for error and don't use bad request - it's not error.

2017-07-16 14:01 UTC, avoytovich commented on server/controllers/donor.controller.js
> +          gift.dataValues.status == 'hasOneDonor' &&
true == 1; // true;
true === 1; // false
its bad idea 'everywhere'. In this case i agree, but not in 
each.dataValues.user_id == every.dataValues.id == some.dataValues.id  // true;
each.dataValues.user_id === every.dataValues.id === some.dataValues.id  // false;
it causes another flow for my program..i don't agree with it at all

2017-07-16 16:56 UTC, denisbodnar submitted a review, later dismissed

2017-07-16 17:31 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-16 18:50 UTC, yarvanya submitted a review, later dismissed

2017-07-17 08:26 UTC, 4asof4ik requested changes

2017-07-17 08:26 UTC, 4asof4ik commented on server/controllers/donor.controller.js
> +        id: req.params.gift_id,
event id add

2017-07-17 08:26 UTC, 4asof4ik commented on server/controllers/donor.controller.js
> +          !gift && res.status(201).json({'message': messages.attempt}) ||
you send response 201 before create  where your logic

2017-07-17 08:59 UTC, avoytovich commented on server/controllers/donor.controller.js
> +          !gift && res.status(201).json({'message': messages.attempt}) ||
i'll change 201 on 403 if i correct understand your assertion

2017-07-17 09:12 UTC, avoytovich commented on server/controllers/donor.controller.js
> +        id: req.params.gift_id,
at the beginning i have only two parameters id for user, and gift_id. Therefore, i can get event_id only from Event where id: gift.dataValues.event_id. i did it in a code below...How i can add event id in gift if i can only retrieve all about event from Gift???

2017-07-17 09:40 UTC, yarvanya commented on server/helper/messages.js
> +  booked: 'Sorry, you have booked this gift already',
It rightly will be:
"Sorry, you have already booked this gift"

2017-07-17 09:41 UTC, yarvanya submitted a review, later dismissed

2017-07-17 13:38 UTC, denisbodnar submitted a review, later dismissed

2017-07-17 15:02 UTC, yurii-kokhalevych submitted a review, later dismissed

2017-07-17 19:42 UTC, 4asof4ik requested changes

2017-07-17 19:42 UTC, 4asof4ik commented on server/controllers/donor.controller.js
> +      .then(donor => {
donors

2017-07-17 19:42 UTC, 4asof4ik commented on server/controllers/donor.controller.js
> +          User.findAll().then(user => {
56-90 spaghetti code

2017-07-17 19:42 UTC, 4asof4ik commented on server/controllers/donor.controller.js
> +    let i = 0;
??

2017-07-17 22:01 UTC, avoytovich commented on server/controllers/donor.controller.js
> +    let i = 0;
done

2017-07-21 07:33 UTC, yarvanya approved these changes

2017-07-21 11:38 UTC, yurii-kokhalevych approved these changes

2017-07-21 11:50 UTC, denisbodnar approved these changes

2017-07-21 14:25 UTC, merged