make working link in emails
Lv-237-NodeJS/api.da-mi pull request #67
Opened 2017-07-12 20:48 UTC by yurii-kokhalevych

## JIRA

* [Main JIRA ticket](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)
* [JIRA subtask](https://ssu-jira.softserveinc.com/browse/LVNOD-XXX)

## Code reviewers

- [ ] @yarvanya
- [ ] @shyyka
- [ ] @yuliannakorol

### Second Level Review

- [ ] @lhalam
- [ ] @4asof4ik

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo
## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2017-07-13 11:27 UTC, avoytovich submitted a review, later dismissed

2017-07-13 20:30 UTC, Vovk-Nazar requested changes

2017-07-13 20:30 UTC, Vovk-Nazar commented on server/helper/constants.js
> +  get URL1() {
change naming for URL and URL1

2017-07-13 21:26 UTC, denisbodnar submitted a review, later dismissed

2017-07-13 21:52 UTC, shyyka submitted a review, later dismissed

2017-07-13 22:13 UTC, avoytovich approved these changes

2017-07-14 05:50 UTC, shyyka approved these changes

2017-07-15 06:55 UTC, 4asof4ik approved these changes

2017-07-15 12:42 UTC, merged